"""rename_google_token_field

Revision ID: e5273fe08a33
Revises: e4e3ad7ef3b9
Create Date: 2026-08-21 16:18:45.611173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5273fe08a33'
down_revision: Union[str, Sequence[str], None] = 'e4e3ad7ef3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('google_access_token', sa.String(), nullable=True))
    op.drop_column('UserProfile', 'google_acess_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('google_acess_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('UserProfile', 'google_access_token')
    # ### end Alembic commands ###
